name: Déployer sur VPS (staging)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1) Prépare le dossier staging sur le VPS
      - name: Préparer le dossier staging sur VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo mkdir -p /opt/portfolio-data-platform-staging
            sudo chown -R ${{ secrets.VPS_USER }} /opt/portfolio-data-platform-staging

      # 2) Copier les fichiers vers staging
      - name: Copier le code vers staging
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          target: "/opt/portfolio-data-platform-staging"

      # 3) Arrêter l’ancienne stack staging (nom de projet staging)
      - name: Arrêter l’ancienne stack staging
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/portfolio-data-platform-staging/infra || exit 0
            docker compose -p staging --env-file ../.env.staging down -v || true

      # 4) Démarrer la nouvelle stack staging avec -p staging
      - name: Démarrer la stack staging
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/portfolio-data-platform-staging/infra || exit 0
            docker compose -p staging --env-file ../.env.staging pull
            docker compose -p staging --env-file ../.env.staging up -d --remove-orphans