name: Déployer sur VPS (production)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Préparer le dossier prod sur VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo mkdir -p /opt/portfolio-data-platform
            sudo chown -R ${{ secrets.VPS_USER }} /opt/portfolio-data-platform
            rm -rf /opt/portfolio-data-platform/*

      - name: Copier les fichiers vers production
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          target: "/opt/portfolio-data-platform"

      - name: Lancer stack production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/portfolio-data-platform/infra || exit 0
            docker compose -p --env-file ../.env.production pull
            docker compose -p --env-file ../.env.production up -d --remove-orphans