# .github/workflows/deploy-staging.yml
name: Déployer sur VPS (staging)

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Préparer le dossier staging sur VPS
        uses: appleboy/ssh-action@v1.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo mkdir -p /opt/portfolio-data-platform-staging
            sudo chown -R ${{ secrets.VPS_USER }} /opt/portfolio-data-platform-staging
            rm -rf /opt/portfolio-data-platform-staging/*

      - name: Copier les fichiers vers staging
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          target: "/opt/portfolio-data-platform-staging"

      - name: Lancer stack staging
        uses: appleboy/ssh-action@v1.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/portfolio-data-platform-staging/infra || exit 0
            docker compose --env-file ../.env.staging pull
            docker compose --env-file ../.env.staging up -d --remove-orphans